http://stackoverflow.com/questions/6826036/cant-activate-mysql2-0-3-6-already-activated-mysql2-0-3-2-in-rails-3-1
LoadError: Please install the mysql2 adapter: `gem install activerecord-mysql2-adapter` (can't activate mysql2 (~> 0.3.10), already activated mysql2-0.4.1. Make sure all dependencies are added to Gemfile.)